from pydantic import BaseModel, Field


class SearchResult(BaseModel):
    """
    Represents a single web search result.
    """

    title: str = Field(
        description="Title of the search result."
    )

    url: str = Field(
        description="Source URL."
    )

    snippet: str = Field(
        description="Short summary of the content."
    )


class SearchResults(BaseModel):
    """
    Collection of search results for one research task.
    """

    query: str

    results: list[SearchResult]

class SearchQuery(BaseModel):
    """
    Optimized query generated by the LLM for web search.
    """

    query: str = Field(
        description="An optimized web search query."
    )