from pathlib import Path

from agents.writer.models import ResearchReport
from services.logger import logger
from datetime import datetime


class ReportExporter:
    """
    Exports research reports to disk.
    """

    OUTPUT_DIR = Path("outputs")

    def __init__(self):
        self.OUTPUT_DIR.mkdir(
            exist_ok=True
        )

    def _safe_filename(
        self,
        title: str,
    ) -> str:

    def export(
        self,
        report: ResearchReport,
    ) -> Path:

        filename = self._safe_filename(report.title)

        path = self.OUTPUT_DIR / filename

        generated_at = datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )
        markdown = f"""# {report.title}

        > Generated by Multi-Agent AI Research Assistant

        **Generated:** {generated_at}

        ---

        # Executive Summary

        {report.executive_summary}

        ---

        # Detailed Analysis

        {report.report}
        """
        path.write_text(
            markdown,
            encoding="utf-8",
        )
        logger.info(f"Report exported successfully: {path}")
        return path