from pydantic import BaseModel, Field


class ResearchReport(BaseModel):
    """
    Final research report generated by the WriterAgent.
    """

    title: str = Field(
        description="Title of the research report."
    )

    executive_summary: str = Field(
        description="A concise summary of the report in 3–5 sentences."
    )

    report: str = Field(
        description="A publication-quality Markdown research report with "
        "well-structured headings, tables where appropriate, "
        "bullet points, citations, and a Sources section."
    )